name: Format
on:
    push:
        paths:
            - "src/**/*.java"
            - "test/**/*.java"
            - ".github/workflows/google_java_format.yml"
    pull_request:
        paths:
            - "src/**/*.java"
            - "test/**/*.java"
            - ".github/workflows/google_java_format.yml"
jobs:
    formatting:
        name: Format
        timeout-minutes: 2
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@4
            -   uses: axel-op/googlejavaformat-action@v3
                with:
                    args: "--replace"
                    skip-commit: true
            -   name: Print diffs
                run: git --no-pager diff --exit-code